### ISSUE TITLE
serving option: drop empty indicators

### ISSUE THREAD

**Issue by semio** [semio/ddf_utils#106]
Indicator with no datapoints is valid, but no practical use. We can provide an option when serving ingredients to disk.

```yaml
procedure: serve
options:
    drop_empty_datapoints: true   # then it will not create empty datapoint csv files.
```

default should be true.
