### ISSUE TITLE
procedure: map and compose

### ISSUE THREAD

**Issue by semio** [semio/ddf_utils#110]
two basic control flow for recipe I missed is `map` and `compose`. `map` applies one function to multiple inputs, and `compose` applies multiple functions to one input.

## map

```yaml
procedure: map
ingredients:
    - a
    - b
    - c
options:
    procedure: filter
    options: 
        filter:
            age: 
                - 10
    result_modifier:
        suffix: "_filtered"
```

So this procedure produce `a_filtered`, `b_filtered`, `c_filtered`.

## compose

```yaml
procedure: compose
ingredients:
    - a
options:
    procedures:
        - procedure: translate_header
          options:
              dictionary: 
                  geo: country
        - procedure: groupby
          options: ...
result: a_transformed
```

This will run translate_header and groupby to `a`

And we should allow to use `map` and `compose` together, i.e. map a composed function to a list of inputs
