### ISSUE TITLE
allow multiple dimensions in final result

### ISSUE THREAD

**Issue by semio** [semio/ddf_utils#27]
sometimes we want to create datasets with multiple keys. Such as a dataset with datapoints by geo, time and also datapoints by geo, gender, time

This feature is not supported yet because:
1. There is only one procedure result for each data type(concepts/datapoints/entities) will be saved to disk
2. the naming of files will follow the key of the result ingredient, but there is only one key for each ingredient.

**Comment by semio** [comment]
there are 2 ways:

1. add an options to procedure that indicates weather the result of the procedure should be save to disk.
2. add a new section in recipe, to set which procedures' results should be the final outputs.

**Comment by semio** [comment]
I think the 2nd way is better, it will make the recipe clear and easy to find which procedure result will be the final output.

So the recipe will look like this:

```yaml
info:
    # basic info
ingredients:
    # list of ingredients
cooking:
    # cooking procedures
    datapoints:
        # datapoint procedures
    entities:
        # datapoint procedures
    concepts:
        # datapoint procedures
dishes:
    datapoints:
        - datapoint_procedure_result_id_1
        - datapoint_procedure_result_id_2
        # and more
    entities:
        # entities procedure result ids
    concepts:
        # entities procedure result ids

**Comment by jheeffer** [comment]
Hmm, I like the third option too.. 

I'm doubting between keeping the cooking procedures per dish separated or allow them to be mixed (as in your example.

Separate cooking per dish forces the writer to work more structured and gives a better overview of what the output is and how the output is produced. 
However, splitting it up doesn't, or would make it harder, to reuse intermediate results of one dish in another.

```
info:
    # basic info
config:
    # configuration
include:
    # other recipes
ingredients:
    # list of ingredients
cooking:
    # cooking procedures
    datapoints:
        - #datapoint procedures for key1
        - #datapoint procedures for key2
        - #datapoint procedures for key3 
    entities:
        - #entity procedures for key4
    concepts:
        - #concept procedures for key5
```

Another question: how important is it according to you to have the datapoints/entities/concepts distinction in the cooking section? Are they useful? And if so, is it just to guide you to write structured recipes or would it not work without it (e.g. introduce ambiguity)?

Also, does this mean the current chef isn't able to construct a dataset with more than one entity domain? Since that would mean different keys for output of entities (e.g. `geo` and `companies`).

**Comment by semio** [comment]
@jheeffer 

# Multiple entity domains

Yes you are right, it's not supported yet. Also for now all concepts will be in ddf--concepts.csv.

# Use of splitting by collection in cooking

in the program there are 2 usage of collection types in cooking section:

* As you said, to tell what filename to output the key-value pairs
* When running the recipe, the procedures will be run by collection. This will make the logs look better. If we don't split up the collections, then when we have a recipe that includes other recipes, the procedures for different collections will mix up and logs will mix up too.

But to achieve above we don't have to add split collections in the recipe. Because we can infer the collection type from the ingredient's key/value, we can make the program to judge types of ingredients and group them by collection. So it's not very important (to the chef) to have split collection in the recipe.

# Dishes

In your suggested recipe format, I don't see the difference to the current format... Do you actually mean this: (you can add `yaml` to triple quotes to make the codes highlighted)

```yaml
cooking:
    # cooking procedures
    datapoints:
        [geo, year, gender]:
            - #datapoint procedures for key1 (geo,year,gender)
        [geo, year]:
            - #datapoint procedures for key2 (geo,year)
        [business, year]:
            - #datapoint procedures for key3 (business,year)
    entities:
        [geo]:
            - #entity procedures for key4 (geo)
        [business]:
            - #entity procedures for key5 (business)
    concepts:
        [concept]:  
            - #concept procedures for key6 (concept)
```

I think this format is good too, because we can have complex keys, like datapoint--by--geo-usa-chn--time.

**Comment by jheeffer** [comment]
**key on top of section**
on the one hand it's clear what each section will contain, on the other hand it can lead to inconsistency: the key at the end of the procedure might not be what is defined at the top.

**reusing intermediate results**
I also want to make sure we can reuse intemediate results in multiple dishes. For example, take population by geo year age gender. Do some pre-processing, then group by & aggregate into different dimensionalities. The pre-processing shouldn't be defined multiple times for each dish.

**separate dishes section**
This is good so you can separate the cooking and the serving. I.e. the data transformation and exact output format. For example choose filename, splitting of dimension values over multiple files or combining multiple indicators in one file.
It does make it more verbose, but we might need it anyway for multi-dimensionality.

**Comment by jheeffer** [comment]
**custom tree structure in cooking**
We could allow cooking section to have a custom tree structure. Then either each end of a leaf is a dish, or dishes still need to be defined in a dishes section.
Example of tree:
```yaml
---
cooking:
  datapoints:
  - procedure: prepare data
    ingredient: popbyagegenderyeargeo
    result: foo
  - procedure: prepare data 2
    ingredient: foo
    result: prepared_pop
  - - procedure: group_by
      ingredient: prepared_pop
      result: sum_gender
      options:
        aggregate:
          population: sum
        group_by:
        - geo
        - year
        - age
  - - procedure: group_by
      ingredient: prepared_pop
      result: sum_age
      options:
        aggregate:
          population: sum
        group_by:
        - geo
        - year
        - gender
```

or

```yaml
---
cooking:
  datapoints:
    procedures:
    - procedure: prepare data
      ingredient: popbyagegenderyeargeo
      result: foo
    - procedure: prepare data 2
      ingredient: foo
      result: prepared_pop
    deeper:
      procedures:
      - procedure: group_by
        ingredient: prepared_pop
        result: sum_gender
        options:
          aggregate:
            population: sum
          group_by:
          - geo
          - year
          - age
    deeper2:
      procedures:
      - procedure: group_by
        ingredient: prepared_pop
        result: sum_age
        options:
          aggregate:
            population: sum
          group_by:
          - geo
          - year
          - gender
```

or 

```yaml
---
cooking:
  datapoints:
    procedures:
    - procedure: prepare data
      ingredient: popbyagegenderyeargeo
      result: foo
    - procedure: prepare data 2
      ingredient: foo
      result: prepared_pop
    children:
      deeper:
        procedures:
        - procedure: group_by
          ingredient: prepared_pop
          result: sum_gender
          options:
            aggregate:
              population: sum
            group_by:
            - geo
            - year
            - age
      deeper2:
        procedures:
        - procedure: group_by
          ingredient: prepared_pop
          result: sum_age
          options:
            aggregate:
              population: sum
            group_by:
            - geo
            - year
            - gender
```
and there's many more variations.

Datapoints/entities/concepts would also just be part of the custom tree. We'd just advice you to use them as base nodes in your tree.

**Comment by jheeffer** [comment]
**Traversing order**
I suppose you're right now traversing procedures sequentially (top-down). And when a procedure refers to an ingredient which hasn't been created yet (but might be later in the recipe) it errors?

**Comment by jheeffer** [comment]
Btw, maybe we need a different solution. Maybe we can learn from other declarative languages.

**Comment by semio** [comment]
**Traversing order**

Yes, for now it's top-down and it will be errors when requiring ingredients not created yet.

But we can change this behavior to bottom-up, or lazy evaluated: When reading the recipe, chef make a list of all available ingredients (including the ones in the `ingredients` section and the ones created by procedure) and when the ingredient is required by some procedure, it then evaluate the data from the ingredient. If the data needs other ingredient, then chef will go on evaluate the data of the other ingredient required. And because the data in ingredients are cached, we won't add complexity by this way.

For reusing intermedia results, we don't have to use tree structure. 

**Custom tree structure**

Using tree structure will work, but I think using nested objects will make the recipes hard to read/write by human, and readability/writability should be one of our goal for recipes, right? 

I see your point to make the leafs the default output of recipe, but we can still use a flat list to achieve this. Because for each procedure result(node), we have to set the base ingredients (parent node), and node ID and parent ID are all we need to build a tree from a list of nodes. See an algorithm [here](https://stackoverflow.com/questions/444296/how-to-efficiently-build-a-tree-from-a-flat-structure) 

So we can write the recipe in list and chef can treat it like a tree.

And suddenly we can keep using the current recipe format and we just need to let chef output the leafs of the tree, right? :D

**Comment by semio** [comment]
A different solution, maybe we can write our own DSL instead of json/yaml. In this way we can define our own syntax and could greatly improve the productivity using recipes. I think it's worth to think about this.

**Comment by jheeffer** [comment]
Yes it should definitely be readable/writable! But how readable is a tree in a flat list? How will readers easily see what the output of the recipe is? You can only know for each ingredient by checking all other procedures if it isn't used as input. 

It's good to make examples in these cases: both for communicating and because building the example will make reiterate your idea.

As for our own format: yes, but I only want to reinvent the wheel when it's a much better wheel that can do things way better than any other wheel out there ;)
The benefit of using a format which many know and has support in many systems is not to be underestimated.
But if you have an idea, of course: post it.

**Comment by jheeffer** [comment]
I thought about lazy evaluation too. It'd work well because all our procedures are pure (no external state changed).
However, for caching: that could mean we have all SG datapoints in memory multiple times... Could become very heavy?

**Comment by semio** [comment]
But there is a problem for writing the recipe as tree, that a node in a tree may need another node from another tree... The tree is more like an inheritance tree. Consider `merge` with 2 ingredients which are intermedia result of other trees. Then I am not sure where to put the procedure in the recipe.

```yaml
# some elements are omitted
- procedure: proc_1
  ingredients: base_ingred_1
  result: result_1
  - - procedure: sub_proc_1
      ingredients: result_1
      result: sub_result_1
- procedure: proc_2
  ingredients: base_ingred_2
  result: result_2
  - - procedure: sub_proc_2
      ingredients: result_2
      result: sub_result_2
- procedure: merge_1  # <= which level should we put this procedure
  ingredients:
    - sub_result_1
    - sub_result_2
  result: merged_result_1
```
