### ISSUE TITLE
new procedure: aggregate datapoints according to dimension's entity-properties

### ISSUE THREAD

**Issue by jheeffer** [semio/ddf_utils#28]
A new procedure should be designed and implemented:

Scenario:
- We have datapoints for entities. For example population of countries (entities) by year

| geo | year | population |
| --- | :-: | --: |
| swe | 2015 | 10 |
| swe | 2016 | 11 |
| chn | 2015 | 20 |
| chn | 2016 | 21 |
| jpn | 2015 | 15 |
| jpn | 2016 | 13 |
- Countries have properties, such as `world_4region`, `geographic_regions`, `income_groups`

| geo | world_4region | geographic_regions | income_groups |
| --- | --- | --- | --- |
| swe | europe | europe | high_income |
| chn | asia | east_asia_pacific | upper_middle_income |
| jpn | asia | east_asia_pacific | high_income |
- We want to aggregate data where we group entities according to the values in one of their entity properties. For example: aggregate the countries by their world_4region using sum

| world_4region | year | population |
| --- | :-: | --: |
| europe | 2015 | 10 |
| asia | 2015 | 35 |
| europe | 2016 | 11 |
| asia | 2016 | 34 |
- These properties, in this case, respond to other entities in other entity sets (world_4region is an entity set). However, this procedure shouldn't care about that for now. They might just as well be strings or another concept type.

**Comment by semio** [comment]
we can add this function to the `groupby` procedure. The current groupby procedure only accept keys in datapoint, but we can change it to also accept entities properties

**Comment by semio** [comment]
So there are 2 steps for this procedure:

1. translate the key column of a **datapoint** ingredient based on the information on an **entity** ingredient
2. doing group by and aggregate on the datapoint

for step 2 we already have a `groupby` procedure;

for step 1, for now we can use `translate_column` with json exported using the entity csv. To do this automatically, we can expand this function, adding a new option to it.

```yaml
datapoints:
    - procedure: translate_column
      result: datapoint-transalted
      options:
            base: geo-domain-entity
            from: geo
            to: world_4region
```

**Comment by jheeffer** [comment]
So with my proposal in https://github.com/semio/ddf_utils/issues/3 this would become

```yaml
datapoints:
    # translate geo to world_4region
    - procedure: translate_column
      ingredients: [datapoints-population]
      column: geo
      dictionary:
          ingredient: geo-domain-entity
          key: world_4region
          value: geo
      result: datapoints-population-translated
    # group by world_4region
    - procedure: groupby
      ingredients: [datapoints-population-translated]
      result: datapoints-population-translated-aggregated
      options:
            by: geo
            aggregate: sum
```
