### ISSUE TITLE
procedure for manual edits

### ISSUE THREAD

**Issue by semio** [semio/ddf_utils#36]
To change cell values, we can use `translate_column` if the cell have value. But what if we want to edit the cell with no content (NaN) or appending new values?

proposal:

```yaml
- procedure: assign_value
  ingredients: [concepts-population]
    options:
      dictionary:  # filename or dictionary {index: {column: assigned_value}}
        population:
          description: "Total population reported by government"
          unit: "Thousands"
  result: concepts-population-edited
```

This is more flex than `translate_column`, because we can change values in any index/column and create new index/column if it doesn't exists.

**Comment by jheeffer** [comment]
Hmm, so this would enable adding concept names, units etc to new concepts, entities etc in the recipe.
I'll think about this, compare it to having an ingredient with these names, units etc and merging that dataset on top of the new one. 
It seems very similar to the merge procedure, but you just build the merge ingredient from bit more complex dictionary.

**Comment by semio** [comment]
Yeah, it should be similar to merging an ontology dataset.

This procedure is easy to implement, so we can leave this one for now and build it when we need it.

**Comment by semio** [comment]
so we need this procedure for SG concepts. 

@jheeffer other than create ontology dataset, I think we can make a new procedure like `merge` but accept csv file as input. I don't like to extend current `merge` for this feature, because they are different, current `merge` should accept multiple ingredients, and create one new ingredient, but the new function takes one ingredient and create one ingredient. What do you think?

**Comment by jheeffer** [comment]
So my thoughts on how we can solve this problem

1. `translate` procedure -> but if source changes a bit, translate will break. Not robust.
2. apply patches -> same problem as `translate` I think
3. ingredients from csv files: allow creating an ingredient from a standalone csv file
4. ingredients from inline data
5. allow ingredient definition on-the-fly in a procedure

example of 4 & 5
```yaml
procedure: merge
ingredients:
- concepts1
- concepts2
- key: concept
  value: description
  data:
  - concept: co2percapita
    description: alternative description
  - concept: co2anotherone
     description: alternative description for co2anotherone
options:
  deep: true
```

example of 3 (can be plugged in to 5 as well)
```yaml
ingredients:
- id: concept_overwrites
  key: concept
  value: description
  data: extracsvfile.csv
```

This borrows heavily from [tabular data resource](https://specs.frictionlessdata.io/tabular-data-resource/) spec.

What do you think of that? On the one hand I'm afraid allowing on-the-fly ingredient definition like that might allow too free-form recipes. Though the freedom can be useful at times.

I don't see how this kind of merging is fundamentally different from normal merging and requires its own procedure like you propose?

**Comment by semio** [comment]
right, fundamentally the new procedure is indeed same as `merge`, they both do merge tables. I didn't think it though last time. Anyways, I think this could be an option too:

6. adding a parameter to `merge` to merge external file

```yaml
procedure: merge
ingredients:
- input_1
- input_2
options:
  external_file: overwrite.csv
```

So we don't need to create new ingredient from a non-DDF file. comparing to point 3 above, the disadvantage is that only the filename is passed, no more information (like the `key`) is provided. 

On point 5: We care about readability, but adding data inline in the procedure might make the recipe hard to read... If we want to support inline data, we better move them to ingredient definition as below. This is what you suggested in point 4, right?

```yaml
ingredient: custom_csv
key: concept
value:
  - description
  - unit
data:
  - concept: co2percapita
    description: alternative description
    unit: tons of c
  - concept: co2anotherone
     description: alternative description for co2anotherone
    unit: tons of co2
```

**Comment by jheeffer** [comment]
Alright, good, so we agree that we don't need a new procedure, `merge` will do right?

Your proposal for an `external_file` option is definitely possible. I guess it would always be added at the end of the ingredient list and you would imply that the csv contains columns with the same header as the primary key of the other ingredients (so you know what columns to merge on).
```
procedure: merge
ingredients:
- input_1
- input_2
options:
  external_file: overwrite.csv
```
The same thing using my proposal would be:
```
procedure: merge
ingredients:
- input_1
- input_2
- data: overwrite.csv
  key: concept
  value: *
```
You could even leave `value: *` out (in any ingredient definition) to imply `value: *`.

Yours is more concise but limiting in order of merging, selection from the csv and might make the merge code complex.
Mine is more rich but verbose and might allow for too much freedom, not pushing towards getting data from the source.
Combining both might be overkill. Should have one way to do something.

I'd go for my option indeed. Let's do all of it. So ingredient from inline data and csv and on-the-fly ingredient definition.
