### ISSUE TITLE
Procedure: Add missing concepts

### ISSUE THREAD

**Issue by jheeffer** [semio/ddf_utils#40]
Procedure to add missing concepts to a concepts ingredient.

Use case:
You create new indicators or properties running operations, aggregates, cumsums etc. These new indicators are not in your dataset yet. They need to be in your concepts table.

```yaml
   - procedure: add_concepts
     ingredient: concepts_incomplete
     result: concepts_complete
     options:
       source_ingredients: ["new_indicators","more_new_indicators"]
```

Takes all concepts mentioned in `source_ingredients` dataframes.
For each concept, if it's not in `ingredient`, add a row for the concept to `ingredient` and add concept_type according to values in that concept (numerical: measure, non-numerical: string).

**Comment by semio** [comment]
@jheeffer I have make the procedure works for datapoint ingredients. 

From your description I assume `source_ingredients` are all datapoint ingredients.  But I think this procedure also applies to adding missing data from entity ingredients, right?

**Comment by jheeffer** [comment]
yes, it could be any ingredient, entity ingredients and even concept ingredients (with concept properties)
datapoints is most important for now

**Comment by jheeffer** [comment]
Maybe we should change this to `merge_concepts`.

```yaml
 - procedure: merge_concepts
   ingredient: concepts_incomplete || null || absent   # base ingredient: if null or ingredient 
                                                       # not given, no base concepts ingredient
   result: concepts_complete
   options:
     source_ingredients: ["new_indicators","more_new_indicators"]
     remove_when_not_in_sources: true || false  # default false. if true, concepts not in source_ingredients 
```

Old functionality stays: for each concept in source ingredients, if concept not in base, add it.
New functionality: if `remove_when_not_in_sources` is true, any concept that was not in sources should not be in result.

When no base-ingredient given or it's null, it is as if it's base-ingredient is empty. So result is simply all concepts in source ingredients.
`remove_when_not_in_sources` probably needs a better name. Maybe other names in this procedure also need to be revised.

**Comment by jheeffer** [comment]
Bug: measures are incorrectly typed as strings

In CJ's dataset, measures are identified as strings by this procedure. See output:
https://github.com/cjbackman/ddf--sodertornsmodellen/blob/master/output/ddf--concepts.csv#L103

https://github.com/cjbackman/ddf--sodertornsmodellen/blob/master/output/ddf--datapoints--immigration_surplus_min_3_years_of_higher_education_aged_25_64_male--by--basomrade--year.csv

Possibly the `-` characters throw the algorithm off, thinking they are strings?

**Comment by semio** [comment]
> Possibly the - characters throw the algorithm off, thinking they are strings?

no, it's because they are Integers but my algorithm only checks floats... I will fix that and make it check any type of numeric data

**Comment by semio** [comment]
how about changing the parameter orders:

```yaml
 - procedure: extract_concepts
   ingredients: 
    - new_indicators
    - more_new_indicators
   result: concepts_complete
   options:
     base_ingredient: concepts_not_complete || null || absent
     join: inner || outer
```

so when `join` is inner then concepts in both new ingredients and base ingredient will be kept, if outer then the union of concepts will be kept.

**Comment by jheeffer** [comment]
I was thinking of joins too but inner join is not the right terminology here. Inner join gives the intersection but our script gives all of source ingredients concepts, even if they don't occur in base.

**Comment by jheeffer** [comment]
For switching ingredients, it's possible, though I thought it would be strange to have non-concept ingredient as main ingredient in a concept procedure... Maybe it's fine though

**Comment by semio** [comment]
Because the name is extract_concepts, it should accept any kind of ingredient and extract concepts in it.. I think using non concept ingredient in main ingredient is ok. 

for joins, yeah, I didn't notice intersection in not we need. So use a new name for this... Maybe `source_only: true || false` ?

**Comment by jheeffer** [comment]
Oh, but actually, what we need is called `right outer join` (if you consider base left and source right)

**Comment by jheeffer** [comment]
```yaml
- procedure: "extract_concepts"
  ingredients: ["foo","bar"]
  options:
    join: 
        base: "concept_ingredient_id"
        type: inner || full_outer || ingredients_outer # default full_outer
```
We could also add base_outer though I don't see the use of that... it's basically just the base.
