### ISSUE TITLE
Procedure: Serve

### ISSUE THREAD

**Issue by jheeffer** [semio/ddf_utils#41]
```
  - procedure: serve
    ingredient: final_ingredient
```

Saves this ingredient to file, for now as is done already:

In case of datapoints, one file per indicator, keys replicated for each file
In case of concepts, one file for the whole ingredient
In case of entities, one file for either the whole domain or entity sets (depending on input).

Later we will add more options for splitting files differently.

**Comment by semio** [comment]
I have added this procedure in chef, and the procedure should use like this:

```yaml
- procedure: serve
  ingredients:
    - ingredient_1
```

**Comment by semio** [comment]
as in #43, we want to add options to serving. so this should become

```yaml
- procedure: serve
  ingredients:
    - id: ingredient_1
      options:
        foo: baz
    - id: ingredient_2
      options: 
        opt: val
```

and

```yaml
serving:
    - id: ingredient_1
      options:
        foo: baz
    - id: ingredient_2
      options: 
        opt: val
```
