### ISSUE TITLE
trend bridge procedure

### ISSUE THREAD

**Issue by semio** [semio/ddf_utils#42]
add bridge procedure base on the method described in this document: https://docs.google.com/document/d/1XDaiuwsiZ3PeiepUMDS0J3fQO9YG2IbRrXpnWY_8YM4/edit

proposal:

```yaml
- procedure: trend_bridge
  ingredients:
    - new_data_ingredient
  options:
    concept: concept_in_new_data
    join_on: time   # the index column to join
    base: old_data_ingredient
    base_concept: concept_in_old_data  # optional, if not set then assume it's same as concept
    bridge_length: 5
  result: data_bridged
```

Note: except for the `join_on` column, other columns should be grouped. So if the datapoint have key 'geo,time', then the data in old & new ingredients will be grouped by 'geo' first and then run the bridge function.

Example data and result of the procedure above:

old_data_ingredient:

| geo | time | concept_in_old_data |
| --- | --- | --- |
| usa | 1990 | 10 |
| usa | 1991 | 10 |
| usa | 1992 | 10 |
| usa | 1993 | 10 |
| usa | 1994 | 10 |
| usa | 1995 | 10 |
| usa | 1996 | 10 |
| usa | 1997 | 10 |
| usa | 1998 | 10 |
| usa | 1999 | 10 |

new_data_ingredient:

| geo | time | concept_in_new_data |
| --- | --- | --- |
| usa | 1995 | 20 |
| usa | 1996 | 20 |
| usa | 1997 | 20 |
| usa | 1998 | 20 |
| usa | 1999 | 20 |
| usa | 2000 | 20 |
| usa | 2001 | 20 |
| usa | 2002 | 20 |
| usa | 2003 | 20 |
| usa | 2004 | 20 |

bridged_data:

| geo | time | concept_in_new_data |
| --- | --- | --- |
| usa | 1990 | 10 |
| usa | 1991 | 12 |
| usa | 1992 | 14 |
| usa | 1993 | 16 |
| usa | 1994 | 18 |
| usa | 1995 | 20 |
| usa | 1996 | 20 |
| usa | 1997 | 20 |
| usa | 1998 | 20 |
| usa | 1999 | 20 |
| usa | 2000 | 20 |
| usa | 2001 | 20 |
| usa | 2002 | 20 |
| usa | 2003 | 20 |
| usa | 2004 | 20 |

**Comment by jheeffer** [comment]
Okay, trying things out here, I'm not 100% sure yet about this.

```yaml
- procedure: trend_bridge
  ingredients:
    - data_ingredient
  options:
    bridge_start:
      ingredient: old_data_ingredient # optional, if not set then assume it's the input ingredient
      column: concept_old_data
    bridge_end:
      ingredient: new_data_ingredient # optional, if not set then assume it's the input ingredient
      column: concept_new_data
    bridge_length: 5         #steps in time. If year, years, if days, days.
    bridge_on: time      # the index column to join
    target_column: concept_in_result # overwrites if exists. creates if not exists. defaults to 'column'
  result: data_bridged
```

 - It should be possible to build a bridge between two concepts in the same ingredient
 - We should choose if we use `column` or `concept` to designate a column/concept in procedures. I think column is easier and fits with other uses in other procedures.
 - This has similarities to rolling/window functions, especially with the "grouping", which you configured with `join_on`, I made it `bridge_on` (let's keep join for [actual joining](http://pandas.pydata.org/pandas-docs/stable/merging.html#database-style-dataframe-joining-merging)?), but maybe we need something else. It'd be good to see how pandas does this (http://pandas.pydata.org/pandas-docs/stable/api.html#window). And align options with our window procedure.

**Comment by semio** [comment]
I suggest that we remove the `column` option and make `column` in `bridge_start` and `bridge_end` mandatory. I think the `column` outside `bridge_start` and `bridge_end` is kinda confusing, because it looks like it is the column in the input ingredient. In this case we can change the default of `target_column` to bridge_end.column. So the format become:

```yaml
- procedure: trend_bridge
  ingredients:
    - data_ingredient                 # optional, if not set defaults to empty ingredient
  options:
    bridge_start:
      ingredient: old_data_ingredient # optional, if not set then assume it's the input ingredient
      column: concept_old_data
    bridge_end:
      ingredient: new_data_ingredient # optional, if not set then assume it's the input ingredient
      column: concept_new_data
    bridge_length: 5                  # steps in time. If year, years, if days, days.
    bridge_on: time                   # the index column to build the bridge with
    target_column: concept_in_result  # overwrites if exists. creates if not exists. defaults to bridge_end.column
  result: data_bridged
```
