### ISSUE TITLE
add option to set data type in recipe ingredient

### ISSUE THREAD

**Issue by semio** [semio/ddf_utils#43]
Problems: 

1. When reading data from datasets, chef don't have options to set data type for columns
2. When writing data into csv, chef don't have options to set data  format for columns 

## input

For example, say we have data like this:

| country_id | time | life_expectancy |
| --- | --- | --- |
| 1 | 1990 | 60 |
| 2 | 1990 | 70 |
| 3 | 1990 | 80 |

When we use chef to read this file, it will guess the data type of each column, so that all of three columns are `int` by default. But if we want to set country_id to `string`, life_expectancy to `float`,  and time to `datatime`, currently there is no way to change the types. To support this feature, we can add options to the ingredient like this:

```yaml
- id: life_expectancy_datapoints
  dataset: example_dataset
  key: 'country_id,time'
  value: '*'
  options:
    dtype:
      country_id: str
      time: datetime
      life_expectancy: float
```

## output

When saving data to csv, we may want to set the format for some columns. Like adjusting floating point precision, and use Upper case for bool values.

Take the above example, if we save the data to disk using chef, then it will be the same as input.

| country_id | time | life_expectancy |
| --- | --- | --- |
| 1 | 1990 | 60 |
| 2 | 1990 | 70 |
| 3 | 1990 | 80 |

But what if we want to have more precision on the `life_expactancy` column like below? There is no way to do this for now.

| country_id | time | life_expectancy |
| --- | --- | --- |
| 1 | 1990 | 60.0 |
| 2 | 1990 | 70.0 |
| 3 | 1990 | 80.0 |

To support this we can add options to serving procedure / section. Or alternatively add a new procedure to convert column format before serving. Not sure which one will be better for now.

```yaml
serving:
    - id: life_expectancy_datapoints
      options:
         formatter:
           life_expectancy:
             precision: 5
```
