### ISSUE TITLE
path in config section

### ISSUE THREAD

**Issue by semio** [semio/ddf_utils#45]
current config section:

```yaml
config:
  ddf_dir: /path/to/ddf/datasets/
  recipe_dir: /path/to/recipes/to/include
  dictionary_dir: /path/to/dictionary/json/files
```

now ddf_dir can be relative dir but it's relative to the dir where we run the `ddf` command. And usually we need to set abs path in ddf_dir. This is not good because changing computer will make the recipe not working.

**Comment by jheeffer** [comment]
One way is to run recipe on the root of the dataset? Force it with a standard recipe path e.g. etl/recipes/main.yaml. is that an option?

**Comment by semio** [comment]
actually the issue is like this:

for example we have 

```yaml
config:
  ddf_dir: /user/semio/Gapminder
ingredients:
  id: population-datapoints
  dataset: ddf--gapminder--population
  key: 'geo,time'
  value: '*'
```

When chef want to read data of the `population-datapoints` ingredient, it will search datapoints from `/user/semio/Gapminder/ddf--gapminder--population` (ddf_dir + dataset of ingredient)

But the path is fixed and we can't run it from other computer.
