### ISSUE TITLE
make ingredient parameter of procedure optional

### ISSUE THREAD

**Issue by semio** [semio/ddf_utils#48]
This problem raise in #42, where we don't need to pass an ingredient as input. 

The easiest way to do for now is make chef support empty `ingredients` parameter. So we need to provide `ingredients` key, but empty value.

```yaml
- procedure: trend_bridge
  ingredients:     # empty ingredient
  result: output_ingredient_id
  options:
    bridge_start:
      ingredient: some_ingredient_id   # optional
      column: concept_in_bridge_start
    bridge_end:
      ingredient: some_ingredient_id_2  # optional
      column: concept_in_bridge_end
    target_column: concept_in_output_ingredient  # optional
```

But then someone may ask: If `ingredients` is optional, should it be in the `options` object? should options in `options` optional, and put the mandatory options outside `options` object?

**Comment by semio** [comment]
If all goes in to options:

```yaml
- procedure: trend_bridge
  result: str
  options:
    ingredient: str, optional
    bridge_start:
      ingredient: str, optional
      column: str
    bridge_end:
      ingredient: str, optional
      column: str
    target_column: str
```

**Comment by semio** [comment]
If we keep all mandatory field outside `options`:

```yaml
- procedure: trend_bridge
  bridge_start:
    ingredient: ingredient_id
    column: str
  bridge_end:
    ingredient: ingredient_id
    column: str
  result: str
  options:
    ingredient: ingredient_id, optional
    target_column: str, optional
```

```yaml
- procedure: merge
  ingredients: list[ingredient_id]
  result: str
  options:
    deep: bool, optional
```

```yaml
- procedure: window
  ingredients:  list[ingredient_id]
  result: str
    window:
      column: str
      size: int or 'expanding'
      min_periods: int, optional
      center: bool, optional
    aggregate: dict
```
