### ISSUE TITLE
procedure to extract entities from datapoints

### ISSUE THREAD

**Issue by semio** [semio/ddf_utils#56]
# use case

as described in #55, when we create a multidimensional datapoint, we want to also add the new entities in the datapoints.

# proposal 

```yaml
procedure: extract_entities
ingredients:
    - input_ingredient
result: output_ingredient
options:
    extract_columns:
        - gender
        - geo
        - foo
```
