### ISSUE TITLE
handling merge/split of a country

### ISSUE THREAD

**Issue by semio** [semio/ddf_utils#58]
Problem:

see https://github.com/open-numbers/ddf--gapminder--co2_emission/issues/1

**Comment by semio** [comment]
current design:

## merge

```yaml
- procedure: merge_entity
  ingredients:
      - input_ingredient
  options:
      dictionary: merge.json
      merged: keep    # what to do with the entities to be merged
      target_column: entity_name
  result: output_ingredient
```

## split



```yaml
- procedure: split_entity
  ingredients:
      - cdiac-datapoints-country-merged
  options:
      dictionary: country_split.json
      splitted: keep
      target_column: nation
      debug: true
  result: cdiac-datapoints-country-merged-splitted
```
