### ISSUE TITLE
suport masking in filter option in ingredient definition and filter procedures

### ISSUE THREAD

**Issue by semio** [semio/ddf_utils#72]
currently the `filter` in ingredient definition and `fliter_item` procedure only select columns when the test returns true, for example

```yaml
ingredients:
  - id: concept_ingredient
    dataset: dataset_id
    key: concept
    filter:
        concept:   # select only concepts which is in the list below
             - concept_1
             - concept_2
```

but when we want to exclude some of ingredient data, it would be hard when there are a lot of data in the ingredient. (In SG, we want to drop 5 indicators, so currently we should write a filter with 500+ rows)

so I think we should add masking option to the filter, to select the columns don't match the filter, by adding another level in the filter, and use keywords `nin`/`in` which I borrow from ddfql

```yaml
ingredients:
  - id: concept_ingredient
    dataset: dataset_id
    key: concept
    filter:
         in:
            concept:   # select only concepts which is in the list below
                 - concept_1
                 - concept_2
```

```yaml
ingredients:
  - id: concept_ingredient
    dataset: dataset_id
    key: concept
    filter:
        nin:
            concept:   # select only concepts which is NOT in the list below
                 - concept_3
                 - concept_4
```
