### ISSUE TITLE
new procedure

### ISSUE THREAD

**Issue by semio** [semio/ddf_utils#94]
Is there a procedure for creating valid id's from another concept?

[3:08 PM]
So I have a `name` property on entities or concepts and want to recreate the entity/concept id's using this `name` property, but processed to a valid id

**Comment by semio** [comment]
This is another way to run translate_column

so we can change translate_column, add `value_modifier` to the dictionary.

```yaml
- procedure: translate_column
  ingredients:
      - input_ingredients
  options:
      column: concept
      target_column: concept
      dictionary:
          base: base_ingredient
          key: name
          value: name
          value_modifier: to_concept_id
```
